---
layout: none
dir_path: netlifycms/collections/
collections:
  - Journal.liquid
  - Article.liquid
  - Author.liquid
  - CallToAction.liquid
---
{% assign path = layout.dir_path | append: "Site.yml" %}

{% include {{ path }} %}

collections:
{% for collection in layout.collections %}
  {% assign path = layout.dir_path | append: collection %}

  {% include {{ path }} %}
{% endfor %}
