require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - vendor/bundle/**/*
    - scripts/**/*
  TargetRubyVersion: 3.2

Style/HashSyntax:
  EnforcedStyle: ruby19
