{% raw %}
backend:
  name: git-gateway
  # repo: agustibr/journal-content
  branch: main
locale: es
local_backend: true

media_folder: "media"

publish_mode: editorial_workflow # Enable drafts

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: &locales [en, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en
{% endraw %}
